# Generated by Django 5.0 on 2023-12-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_post_published_date_metadata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'content', 'author')},
        ),
    ]
