# Generated by Django 5.0 on 2023-12-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_data',
            new_name='update_date',
        ),
    ]
