# Generated by Django 5.0 on 2023-12-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-name'], 'verbose_name': 'Author Name'},
        ),
    ]
